### ISSUE TITLE
sameWindow oauth login does not fire auth:login-success event 

### ISSUE THREAD

**Issue by nbrustein** [lynndylanhurley/ng-token-auth#198]
login-success is fired from submitLogin and handlePostMessage, but when using the sameWindow option with oauth login, the validation happens through validateToken, and `login-success` never gets fired.

A workaround in some cases is to watch for the `auth:validation-success` event, but that gets fired when a user is validated, not only when they login. (So if a user has credentials stored in a cookie or local storage when they first open the page, validation-success will be fired, even though they never logged in.

Seems like it should be safe for validateUser to fire the login-success event if it is in the block that is pulling credentials off of the location.search() params, but I haven't thought about it all that hard.

**Comment by abhayastudios** [comment]
+1

In my code I am listening to the auth:login-success event to change the state, so when a user logs in through OAuth and the sameWindow is used the user never reaches the intended post login state.

**Comment by gee-forr** [comment]
+1 we have the same problem :(

**Comment by shawncmu** [comment]
+1 we have the same problem. I think the problem is inside omniauth controller generating a bad url path that redirected us to a bad page.

**Comment by angelxmoreno** [comment]
i think this issue is resolved now, correct @nbrustein ? can we close this if so?

**Comment by dgoradia** [comment]
@angelxmoreno I don't think it's resolved. `auth:login-success` still not firing in 0.0.29 and devise_token_auth 0.1.37.
